export const data = [
  {
    id: 0,
    plate_no: "MNA-350-MC",
    hit_and_run: "7",
    bad_driving: "9",
    car_theft: false,
  },
  {
    id: 1,
    plate_no: "MNA-389-ZR",
    hit_and_run: "4",
    bad_driving: "3",
    car_theft: true,
  },
  {
    id: 2,
    plate_no: "MNA-340-SR",
    hit_and_run: "2",
    bad_driving: "4",
    car_theft: false,
  },
  {
    id: 3,
    plate_no: "MNA-350-FX",
    hit_and_run: "5",
    bad_driving: "6",
    car_theft: true,
  },
  {
    id: 4,
    plate_no: "MNA-334-AC",
    hit_and_run: "6",
    bad_driving: "5",
    car_theft: true,
  },
  {
    id: 5,
    plate_no: "MNA-435-FC",
    hit_and_run: "3",
    bad_driving: "3",
    car_theft: false,
  },
];
export const graphlogsdata = [
  {
    Location: "Gidan Kwano",
    id: "1",
    timein: "12:45am",
    timeout: "01:00pm",
    date: "07/02/2023",
    vehicleplate: "AGL 621FR",
  },
  {
    Location: "Chanchaga",
    id: "2",
    timein: "10:00am",
    timeout: "12:00pm",
    date: "09/02/2023",
    vehicleplate: "MGL 234GK",
  },
  {
    Location: "Maitumbi",
    id: "3",
    timein: "02:10pm",
    timeout: "02:58pm",
    date: "10/02/2023",
    vehicleplate: "UAC 456MA",
  },
  {
    Location: "Maikunkele",
    id: "4",
    timein: "08:00am",
    timeout: "08:25am",
    date: "11/02/2023",
    vehicleplate: "AGL 621FF",
  },
];
