export const data = [
  {
    id: 0,
    plate_no: "MNA-350-Mc",
    lat: "4.0204",
    long: "5.84939",
    date_time: new Date().toISOString(),
    crime: "overspeeding",
  },
  {
    id: 1,
    plate_no: "MNA-389-zr",
    lat: "4.0204",
    long: "5.84939",
    date_time: new Date().toISOString(),
    crime: "overspeeding",
  },
  {
    id: 2,
    plate_no: "MNA-340-sr",
    lat: "4.0204",
    long: "5.84939",
    date_time: new Date().toISOString(),
    crime: "overspeeding",
  },
  {
    id: 3,
    plate_no: "MNA-350-fx",
    lat: "4.0204",
    long: "5.84939",
    date_time: new Date().toISOString(),
    crime: "overspeeding",
  },
  {
    id: 4,
    plate_no: "MNA-334-ac",
    lat: "4.0204",
    long: "5.84939",
    date_time: new Date().toISOString(),
    crime: "overspeeding",
  },
  {
    id: 5,
    plate_no: "MNA-435-fc",
    lat: "4.0204",
    long: "5.84939",
    date_time: new Date().toISOString(),
    crime: "overspeeding",
  },
];
